name: FareLens
options:
  bundleIdPrefix: com.astrionstudio
  deploymentTarget:
    iOS: "26.0"
  developmentLanguage: en
  xcodeVersion: "16.0"
  groupSortPosition: top

settings:
  base:
    DEVELOPMENT_TEAM: ""
    IPHONEOS_DEPLOYMENT_TARGET: "26.0"
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: 1
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  FareLens:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    info:
      path: FareLens/Resources/Info.plist
      properties:
        CFBundleDisplayName: FareLens
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIBackgroundModes:
          - fetch
    sources:
      - path: FareLens
        excludes:
          - "Resources/Info.plist"
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.astrionstudio.farelens
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: true
        DEVELOPMENT_ASSET_PATHS: ""
        INFOPLIST_FILE: FareLens/Resources/Info.plist
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: false
        SWIFT_EMIT_LOC_STRINGS: true
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: false

  FareLensTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - FareLensTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.astrionstudio.farelens.tests
        BUNDLE_LOADER: $(TEST_HOST)
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/FareLens.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/FareLens
        SWIFT_EMIT_LOC_STRINGS: false
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: FareLens

schemes:
  FareLens:
    build:
      targets:
        FareLens: all
        FareLensTests: [test]
    run:
      config: Debug
      environmentVariables:
        - variable: OS_ACTIVITY_MODE
          value: disable
          isEnabled: false
      commandLineArguments:
        "NSDoubleLocalizedStrings": false
      disableMainThreadChecker: false
      disableThreadPerformanceChecker: false
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - FareLens
      targets:
        - name: FareLensTests
          parallelizable: true
          randomExecutionOrder: false
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
